# Generated by Django 4.0.4 on 2022-05-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_category_favorite_description_book_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
